spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.1"

accounts:
  message: "Welcome to EazyBank accounts related PROD APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384